### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by mbanco** [scipopt/MatlabSCIPInterface#2] opened 2021-12-07 15:18 UTC
Hi,
This is the error it throws when I try to install Opti:

 matlabSCIPInterface_install

Searching for SCIP install ...
Checking environment variables SCIPOPTDIR and SCIPDIR ...
SCIPDIR variable found.

Setting SCIP directory to 'C:/Program Files/SCIPOptSuite'.

SCIP install using 'make install' or '.exe' detected.
Was the specified SCIP library build using cmake/.exe? (y/n)y

------------------------------------------------
SCIP MEX FILE INSTALL

MEX Call:
mex  -largeArrayDims   -DNO_CONFIG_HEADER scip/scipmex.cpp scip/scipeventmex.cpp scip/scipnlmex.cpp -Iscip/Include -I'C:/Program Files/SCIPOptSuite/include' -I'C:/Program Files/SCIPOptSuite/include/blockmemshell' -Iopti  -IInclude -L'C:/Program Files/SCIPOptSuite/lib/' -lscip  -L'C:\\Program Files\\Polyspace\\R2021a\extern\lib\win64\mingw64' -lut  -output scip -DML_VER=R2021a -DOPTI_VER=3.00

Building with 'Microsoft Visual C++ 2019'.
MEX completed successfully.
Done!

------------------------------------------------
INSTALLING Matlab-SCIP Interface ...

- Checking MATLAB version and operating system ...
MATLAB (R2021a) 64bit (Windows x64) detected.

- Checking MEX file release information ...
416 OK = true;
MEX file is not compatible with this version of the Interface.
Error using matlabSCIPInterface_install>mexFileCheck (line 406)
MEX file incompatible.

Error in matlabSCIPInterface_install (line 88)
if (~mexFileCheck(localVer))

Thanks in advance!

**Comment by nsimon-TUDa** [comment] 2021-12-10 17:08
Hi,
this error occurs if the generated mex-file is not working as intended.  For further information please evaluate the mex-file you built with matlab by running the matlab command
`eval scip`
in the directory where the generated mex-file is located.

**Comment by mbanco** [comment] 2021-12-10 17:27
Hi,
when running the command "eval scip" this is the error it throws:

Invalid MEX-file 'C:\MATLAB\work\MatlabSCIPInterface\scip.mexw64': The specified module can not be found.

Best Regards.

**Comment by nsimon-TUDa** [comment] 2021-12-14 11:02
Hi,
the error itself occurs if a library is missing.  After looking into it, the most likely culprit is the C++ utilities library link in your mex command, which currently links against the location of matlabs internal C++ addon. Since you are using another C++ compiler, you might not even have this addon and thus the linked library does not exist.
This is an oversight in the installation script and I will push a fix for that problem later today, after it has been tested. Thanks for bringing it to my attention.

If you have the matlab C++ addon installed, then the error might also occur because of another library link not working correctly. If the other paths in the mex command are set correctly, you can check for further problems with a software like dependency walker.

Edit: The fix might take a few days since I need to setup additional testing environments for Windows installs.

**Comment by nsimon-TUDa** [comment] 2021-12-21 18:06
Hi,
after some further testing it seems unlikely that the utility library is the cause of your problem. The mingw version of the utilities library seems to be delivered with base matlab and not with the matlab mingw compiler, so it should be present on your system as well and thus should not cause a broken link.
I also could not reproduce your error on a fresh windows installation with just Base Matlab, Visual C++ 2019 and the ScipOptSuite installed.
Could you please check if the paths to SCIP are set correctly? Also ensure that the scip library is a shared library (libscip.lib) and not static (.dll).

**Comment by mbanco** [comment] 2021-12-22 15:17
Hi,
I have installed the MinGW64 Compiler but it throws the following error:

>> mex -setup
MEX configured to use 'MinGW64 Compiler (C)' for C language compilation.

To choose a different C compiler, select one from the following:
MinGW64 Compiler (C)  mex -setup:C:\Users\EPRE\AppData\Roaming\MathWorks\MATLAB\R2021a\mex_C_win64.xml C
Microsoft Visual C++ 2019 (C)  mex -setup:'C:\Program Files\Polyspace\R2021a\bin\win64\mexopts\msvc2019.xml' C

To choose a different language, select one from the following:
 mex -setup C++ 
 mex -setup FORTRAN
>> matlabSCIPInterface_install

Searching for SCIP install ...
Checking environment variables SCIPOPTDIR and SCIPDIR ...
SCIP not found! Would you like to specify a custom install location? (y/n)y
Please specify SCIP directory:
Setting SCIP directory to 'C:/Program Files/SCIPOptSuite'.

SCIP install using 'make install' or '.exe' detected.
Was the specified SCIP library build using cmake/.exe? (y/n)y

------------------------------------------------
SCIP MEX FILE INSTALL

MEX Call:
mex  -largeArrayDims   -DNO_CONFIG_HEADER scip/scipmex.cpp scip/scipeventmex.cpp scip/scipnlmex.cpp -Iscip/Include -I'C:/Program Files/SCIPOptSuite/include' -I'C:/Program Files/SCIPOptSuite/include/blockmemshell' -Iopti  -IInclude -L'C:/Program Files/SCIPOptSuite/lib/' -lscip  -L'C:\\Program Files\\Polyspace\\R2021a\extern\lib\win64\mingw64' -lut  -output scip -DML_VER=R2021a -DOPTI_VER=3.00

Building with 'Microsoft Visual C++ 2019'.
MEX completed successfully.
Done!

------------------------------------------------
INSTALLING Matlab-SCIP Interface ...

- Checking MATLAB version and operating system ...
MATLAB (R2021a) 64bit (Windows x64) detected.

- Checking MEX file release information ...
MEX file is not compatible with this version of the Interface.
Error using matlabSCIPInterface_install>mexFileCheck (line 406)
MEX file incompatible.

Error in matlabSCIPInterface_install (line 88)
if (~mexFileCheck(localVer))
 
How do I make sure the SCIP library is a shared library (libscip.lib)?

Best Regards.

**Comment by nsimon-TUDa** [comment] 2021-12-23 15:18
Hi,

to check if the scip library is a shared library just check if it is called libscip.lib,  if you installed SCIP via the installer, then it should be installed as a shared library.

But I managed to replicate your error today by removing SCIP from the Windows environment variables. Could you check whether the path 'C:\Program Files\SCIPOptSuite\bin' is included in the 'Path' Environment Variable of your System?
If not, add it, restart Matlab and then try again. Alternatively, during the SCIP installation process, you can also specify that the Installer for SCIP should modify the path variable during install.

Best Regards

**Comment by mbanco** [comment] 2021-12-23 15:52
Hi,
I included the path 'C:\Program Files\SCIPOptSuite\bin' in the Path environment variable and it worked perfectly.

Thanks a lot!

**Comment by nsimon-TUDa** [comment] 2021-12-23 16:53
No problem, thanks for trying out the interface.
I`ll close this issue and update the readme for the windows install.

Happy holidays!

**Closed as completed by nsimon-TUDa** 2021-12-23 16:53 UTC
